project:
  type: website
  render:
  - "!01.1-pregeocoding.qmd"
  - "01*.qmd"
  - "*.qmd"

website:
  title: "Short site name"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - auto: "*.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap